export type KeywordId = `${string}_${number}`; // GenreName_KeywordTMDBId

export type Keyword = {
  id: KeywordId;
  label: string;
};

export type TasteGenre = {
  id: number;
  name: string;
  emoji: string;
  mediaType: 'movie' | 'series' | 'shared';
  keywords: Keyword[];
};

export const TASTE_GENRES: TasteGenre[] = [
  {
    id: 28,
    name: 'Action',
    emoji: '💥',
    mediaType: 'movie',
    keywords: [
      { id: 'Action_188955', label: 'Fist Fights' },
      { id: 'Action_155030', label: 'Superhero Teams' },
      { id: 'Action_1501', label: 'Hidden Meanings' },
      { id: 'Action_2095', label: 'Bad Guys Who Do Good' },
    ],
  },
  {
    id: 12,
    name: 'Adventure',
    emoji: '🏕️',
    mediaType: 'movie',
    keywords: [
      { id: 'Adventure_3289', label: 'Bad Guys' },
      { id: 'Adventure_180734', label: 'Masked Heroes' },
    ],
  },
  {
    id: 14,
    name: 'Fantasy',
    emoji: '🧙‍♂️',
    mediaType: 'movie',
    keywords: [
      { id: 'Fantasy_2343', label: 'Magic' },
      { id: 'Fantasy_616', label: 'Witches' },
      { id: 'Fantasy_269233', label: 'Good vs Bad' },
      { id: 'Fantasy_177912', label: 'Wizards' },
      { id: 'Fantasy_162846', label: 'Ghosts' },
      { id: 'Fantasy_336530', label: 'Teen Magic' },
      { id: 'Fantasy_170362', label: 'Magic Worlds' },
      { id: 'Fantasy_14643', label: 'Big Battles' },
    ],
  },
  {
    id: 36,
    name: 'History',
    emoji: '🏛️',
    mediaType: 'movie',
    keywords: [
      { id: 'History_5565', label: 'Real People' },
      { id: 'History_192772', label: 'Drama in the Past' },
      { id: 'History_12995', label: 'Fake History' },
      { id: 'History_15060', label: 'Old Timey Drama' },
      { id: 'History_207883', label: '1940s' },
      { id: 'History_11001', label: 'Religion' },
      { id: 'History_9725', label: 'Sword Fights' },
      { id: 'History_158718', label: 'LGBTQ+' },
    ],
  },
  {
    id: 27,
    name: 'Horror',
    emoji: '👻',
    mediaType: 'movie',
    keywords: [
      { id: 'Horror_256183', label: 'Ghosts & Demons' },
      { id: 'Horror_295907', label: 'Mind Games' },
      { id: 'Horror_315058', label: 'Scary' },
      { id: 'Horror_1299', label: 'Monsters' },
      { id: 'Horror_4720', label: 'Cults & Rituals' },
      { id: 'Horror_50009', label: 'Trying to Survive' },
      { id: 'Horror_10714', label: 'Serial Killers' },
      { id: 'Horror_12339', label: 'Slashers' },
    ],
  },
  {
    id: 10402,
    name: 'Music',
    emoji: '🎸',
    mediaType: 'movie',
    keywords: [
      { id: 'Music_4344', label: 'Musicals' },
      { id: 'Music_4048', label: 'Musicians' },
      { id: 'Music_6029', label: 'Concerts' },
      { id: 'Music_10229', label: 'Singers' },
      { id: 'Music_246', label: 'Dancing' },
      { id: 'Music_3490', label: 'Pop Stars' },
      { id: 'Music_578', label: 'Rock & Roll' },
    ],
  },
  {
    id: 10749,
    name: 'Romance',
    emoji: '💖',
    mediaType: 'movie',
    keywords: [
      { id: 'Romance_9673', label: 'Love' },
      { id: 'Romance_158713', label: 'Kinky' },
      { id: 'Romance_324429', label: 'Romantic' },
      { id: 'Romance_304976', label: 'Sad Romance' },
      { id: 'Romance_1664', label: 'Steamy' },
      { id: 'Romance_3691', label: 'Secret Love' },
      { id: 'Romance_10614', label: 'Tragic Ending' },
      { id: 'Romance_267122', label: 'Sex' },
      { id: 'Romance_697', label: 'Losing a Partner' },
      { id: 'Romance_34094', label: 'Cheating' },
    ],
  },
  {
    id: 878,
    name: 'Science Fiction',
    emoji: '👽',
    mediaType: 'movie',
    keywords: [
      { id: 'Science Fiction_4565', label: 'Ruined World' },
      { id: 'Science Fiction_33637', label: 'Superpowers' },
      { id: 'Science Fiction_3801', label: 'Space Travel' },
      { id: 'Science Fiction_9882', label: 'Space' },
      { id: 'Science Fiction_310', label: 'AI & Robots' },
      { id: 'Science Fiction_348204', label: 'Bleak Future' },
      { id: 'Science Fiction_1308', label: 'Secret Identity' },
    ],
  },
  {
    id: 10770,
    name: 'TV Movie',
    emoji: '📺',
    mediaType: 'movie',
    keywords: [
      { id: 'TV Movie_6270', label: 'High School' },
      { id: 'TV Movie_65', label: 'Holidays' },
      { id: 'TV Movie_10244', label: 'From a Cartoon' },
      { id: 'TV Movie_931', label: 'Jealousy' },
      { id: 'TV Movie_264598', label: 'TV Special' },
    ],
  },
  {
    id: 53,
    name: 'Thriller',
    emoji: '🤯',
    mediaType: 'movie',
    keywords: [
      { id: 'Thriller_5265', label: 'Spies' },
      { id: 'Thriller_10292', label: 'Blood & Guts' },
      { id: 'Thriller_10085', label: 'Backstabbing' },
      { id: 'Thriller_314730', label: 'Edge of Your Seat' },
      { id: 'Thriller_10349', label: 'Survival' },
      { id: 'Thriller_12377', label: 'Zombies' },
    ],
  },
  {
    id: 10752,
    name: 'War',
    emoji: '⚔️',
    mediaType: 'movie',
    keywords: [
      { id: 'War_1956', label: 'WW2' },
      { id: 'War_13065', label: 'Soldiers' },
      { id: 'War_273967', label: 'War' },
      { id: 'War_2652', label: 'Nazis' },
      { id: 'War_2957', label: 'Vietnam War' },
      { id: 'War_6092', label: 'Army' },
      { id: 'War_162365', label: 'Military' },
      { id: 'War_1701', label: 'Heroes' },
    ],
  },
  {
    id: 10759,
    name: 'Action & Adventure',
    emoji: '🦸‍♂️',
    mediaType: 'series',
    keywords: [
      { id: 'Action & Adventure_322942', label: 'Adventure' },
      { id: 'Action & Adventure_9715', label: 'Superheroes' },
      { id: 'Action & Adventure_779', label: 'Martial Arts' },
    ],
  },
  {
    id: 10762,
    name: 'Kids',
    emoji: '🧸',
    mediaType: 'series',
    keywords: [
      { id: 'Kids_6513', label: 'Cartoons' },
      { id: 'Kids_259376', label: 'Playful' },
      { id: 'Kids_178898', label: 'Cartoon Dogs' },
      { id: 'Kids_18257', label: 'Learning' },
      { id: 'Kids_164246', label: 'Nostalgia' },
    ],
  },
  {
    id: 10763,
    name: 'News',
    emoji: '📰',
    mediaType: 'series',
    keywords: [
      { id: 'News_6078', label: 'Politics' },
      { id: 'News_169086', label: 'Making Fun of Politics' },
      { id: 'News_193164', label: 'Current Events' },
      { id: 'News_191509', label: 'News' },
      { id: 'News_13384', label: 'Morning Shows' },
      { id: 'News_239647', label: 'Magazine Shows' },
      { id: 'News_195207', label: 'Panel Shows' },
      { id: 'News_33847', label: 'UK Politics' },
    ],
  },
  {
    id: 10764,
    name: 'Reality',
    emoji: '🎥',
    mediaType: 'series',
    keywords: [
      { id: 'Reality_194610', label: 'Variety Shows' },
      { id: 'Reality_271', label: 'Competitions' },
      { id: 'Reality_250845', label: 'Reality Contests' },
      { id: 'Reality_291807', label: 'Reality TV' },
      { id: 'Reality_4325', label: 'Game Shows' },
      { id: 'Reality_15479', label: 'Fashion' },
      { id: 'Reality_167198', label: 'Fashion Shows' },
      { id: 'Reality_6383', label: 'Music Contests' },
      { id: 'Reality_186120', label: 'Singing Contests' },
      { id: 'Reality_40870', label: 'Racing' },
    ],
  },
  {
    id: 10765,
    name: 'Sci-Fi & Fantasy',
    emoji: '🚀',
    mediaType: 'series',
    keywords: [
      { id: 'Sci-Fi & Fantasy_6152', label: 'Supernatural' },
      { id: 'Sci-Fi & Fantasy_293198', label: 'Fantasy' },
      { id: 'Sci-Fi & Fantasy_9951', label: 'Aliens' },
    ],
  },
  {
    id: 10766,
    name: 'Soap',
    emoji: '🧼',
    mediaType: 'series',
    keywords: [
      { id: 'Soap_199262', label: 'Telenovelas' },
      { id: 'Soap_291959', label: 'Soap Operas' },
      { id: 'Soap_11612', label: 'Hospitals' },
      { id: 'Soap_316421', label: 'Drama' },
      { id: 'Soap_13005', label: 'Doctors' },
      { id: 'Soap_208788', label: 'Medical Drama' },
      { id: 'Soap_193400', label: 'Teen Drama' },
      { id: 'Soap_237462', label: 'Rich Families' },
      { id: 'Soap_9840', label: 'Romance' },
      { id: 'Soap_11157', label: 'Fighting Siblings' },
    ],
  },
  {
    id: 10767,
    name: 'Talk',
    emoji: '💬',
    mediaType: 'series',
    keywords: [
      { id: 'Talk_3741', label: 'Talk Shows' },
      { id: 'Talk_242216', label: 'Late Night Shows' },
      { id: 'Talk_6562', label: 'Celebs' },
      { id: 'Talk_234957', label: 'Celeb Interviews' },
      { id: 'Talk_320420', label: 'Funny' },
      { id: 'Talk_198299', label: 'Live Music' },
      { id: 'Talk_276775', label: 'Edgy Humor' },
      { id: 'Talk_325830', label: 'Educational' },
      { id: 'Talk_225273', label: 'K-Pop' },
      { id: 'Talk_197715', label: 'Talking' },
    ],
  },
  {
    id: 10768,
    name: 'War & Politics',
    emoji: '⚖️',
    mediaType: 'series',
    keywords: [
      { id: 'War & Politics_15126', label: 'History' },
      { id: 'War & Politics_10046', label: 'Giant Robots' },
      { id: 'War & Politics_321464', label: 'Intense' },
      { id: 'War & Politics_13015', label: 'Terrorism' },
      { id: 'War & Politics_264792', label: 'Politics' },
    ],
  },
  {
    id: 16,
    name: 'Animation',
    emoji: '🐭',
    mediaType: 'shared',
    keywords: [
      { id: 'Animation_207826', label: 'Anime Action' },
      { id: 'Animation_11477', label: 'Talking Animals' },
      { id: 'Animation_161919', label: 'Adult Cartoons' },
    ],
  },
  {
    id: 35,
    name: 'Comedy',
    emoji: '😂',
    mediaType: 'shared',
    keywords: [
      { id: 'Comedy_193171', label: 'Sitcoms' },
      { id: 'Comedy_325765', label: 'Funny' },
      { id: 'Comedy_325782', label: 'Happy' },
      { id: 'Comedy_380', label: 'Siblings' },
    ],
  },
  {
    id: 80,
    name: 'Crime',
    emoji: '🕵️‍♂️',
    mediaType: 'shared',
    keywords: [
      { id: 'Crime_6149', label: 'Cops' },
      { id: 'Crime_703', label: 'Detectives' },
      { id: 'Crime_9826', label: 'Murder' },
      { id: 'Crime_268067', label: 'Police Cases' },
      { id: 'Crime_242', label: 'NYC' },
      { id: 'Crime_9748', label: 'Revenge' },
      { id: 'Crime_12670', label: 'LA' },
      { id: 'Crime_10291', label: 'Mob & Mafia' },
      { id: 'Crime_207268', label: 'Dark Crime' },
      { id: 'Crime_3149', label: 'Gangsters' },
    ],
  },
  {
    id: 99,
    name: 'Documentary',
    emoji: '📜',
    mediaType: 'shared',
    keywords: [
      { id: 'Documentary_4434', label: 'Interviews' },
      { id: 'Documentary_18330', label: 'Nature' },
      { id: 'Documentary_33722', label: 'True Crime' },
      { id: 'Documentary_159290', label: 'Sports Docs' },
      { id: 'Documentary_282080', label: 'Documentaries' },
      { id: 'Documentary_221355', label: 'Nature Docs' },
      { id: 'Documentary_246377', label: 'Music Docs' },
      { id: 'Documentary_325761', label: 'Inspiring' },
      { id: 'Documentary_13042', label: 'Soccer' },
      { id: 'Documentary_155477', label: 'Softcore' },
    ],
  },
  {
    id: 18,
    name: 'Drama',
    emoji: '💔',
    mediaType: 'shared',
    keywords: [
      { id: 'Drama_189402', label: 'Solving Crimes' },
      { id: 'Drama_157241', label: 'Hunting Criminals' },
      { id: 'Drama_311315', label: 'Heavy Drama' },
    ],
  },
  {
    id: 10751,
    name: 'Family',
    emoji: '🏡',
    mediaType: 'shared',
    keywords: [
      { id: 'Family_6054', label: 'Friends' },
      { id: 'Family_18035', label: 'Family' },
      { id: 'Family_10683', label: 'Growing Up' },
      { id: 'Family_18165', label: 'Animals' },
    ],
  },
  {
    id: 9648,
    name: 'Mystery',
    emoji: '🤫️',
    mediaType: 'shared',
    keywords: [
      { id: 'Mystery_5340', label: 'Investigations' },
      { id: 'Mystery_161982', label: 'Solving Murders' },
      { id: 'Mystery_207046', label: 'Who Did It?' },
    ],
  },
  {
    id: 37,
    name: 'Western',
    emoji: '🤠',
    mediaType: 'shared',
    keywords: [
      { id: 'Western_207928', label: '1800s' },
      { id: 'Western_155573', label: 'Wild West' },
      { id: 'Western_2752', label: 'Ranches' },
      { id: 'Western_10322', label: 'Native Americans' },
      { id: 'Western_798', label: 'Sheriffs' },
      { id: 'Western_1556', label: 'Texas' },
      { id: 'Western_801', label: 'Bounty Hunters' },
      { id: 'Western_75', label: 'Gunslingers' },
      { id: 'Western_155291', label: 'Cowboys' },
      { id: 'Western_9503', label: 'Outlaws' },
    ],
  },
];
