name: Deploy to EC2 using ECR + SSM

on:
  push:
    branches:
      - preview
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      BUILD_ENV: ${{ github.ref_name }}
      IMAGE_TAG: ${{ github.ref_name }}-${{ github.run_number }}
      ECR_BASE_URL: ${{ secrets.ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Populate local envs
        run: |
          cp .env.${{ env.BUILD_ENV }} .env.local
          echo "TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}" >> .env.local
          echo "OMDB_API_KEY=${{ secrets.OMDB_API_KEY }}" >> .env.local
          echo "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}" >> .env.local

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region ${{ vars.AWS_REGION }} \
            | docker login --username AWS --password-stdin \
              ${{ env.ECR_BASE_URL }}


      - name: Build and Push Docker image
        run: |
          echo "${{ secrets.SENTRY_AUTH_TOKEN }}" > sentry_token.txt

          docker build \
          --build-arg BUILD_ENV=${{ env.BUILD_ENV }} \
           --secret id=sentry_token,src=sentry_token.txt \
            -t ${{ env.ECR_BASE_URL }}/${{ secrets.ECR_REPO }}:${{ env.IMAGE_TAG }} \
            .
          
          docker push ${{ env.ECR_BASE_URL }}/${{ secrets.ECR_REPO }}:${{ env.IMAGE_TAG }}
          
          rm -rf sentry_token.txt

      - name: Trigger EC2 Deploy via SSM
        uses: debugger24/action-aws-ssm-run-command@v1
        with:
          aws-region: ${{ vars.AWS_REGION }}
          instance-ids: ${{ secrets.EC2_INSTANCE_ID }}
          working-directory: /home/ubuntu
          comment: "Deploy meowie backend - ${{ env.BUILD_ENV }}"
          commands: |
            IMAGE="${{ env.ECR_BASE_URL }}/${{ secrets.ECR_REPO }}:${{ env.IMAGE_TAG }}"
            docker pull $IMAGE && \
            docker stop meowie-${{ env.BUILD_ENV }} || true && docker rm meowie-${{ env.BUILD_ENV }} || true && \
            docker run -d --name meowie-${{ env.BUILD_ENV }} \
            --env-file .env.local \
            -p \$PORT:\$PORT $IMAGE" \
