name: Deploy to AWS Lambda

on:
  push:
    branches:
      - preview
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    env:
      DOCKER_BUILDKIT: 1
      BUILD_ENV: ${{ github.ref_name }}
      IMAGE_TAG: ${{ github.ref_name }}-${{ github.run_number }}
      ECR_BASE_URL: ${{ secrets.ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com
      # Construct the Function Name dynamically based on branch (meowie-production or meowie-preview)
      LAMBDA_FUNCTION_NAME: meowie-${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Docker Setup ---
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region ${{ vars.AWS_REGION }} \
            | docker login --username AWS --password-stdin \
              ${{ env.ECR_BASE_URL }}

      # --- Sentry Setup ---
      - name: Upload source maps to Sentry
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          npm ci
          npm run build
          npm run sentry:sourcemaps

      # --- Build & Push ---
      - name: Build and Push Docker image
        run: |
          docker build \
            --platform linux/arm64 \
            --build-arg BUILD_ENV=${{ env.BUILD_ENV }} \
            -t ${{ env.ECR_BASE_URL }}/${{ secrets.ECR_REPO }}:${{ env.IMAGE_TAG }} \
            .
          
          docker push ${{ env.ECR_BASE_URL }}/${{ secrets.ECR_REPO }}:${{ env.IMAGE_TAG }}

      # --- DEPLOYMENT STEP ---
      # --- STEP 1: Update the Code (Image) ---
      - name: Update Lambda Code
        run: |
          echo "Deploying new image to function: ${{ env.LAMBDA_FUNCTION_NAME }}..."
          
          aws lambda update-function-code \
            --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
            --image-uri ${{ env.ECR_BASE_URL }}/${{ secrets.ECR_REPO }}:${{ env.IMAGE_TAG }}
          
          # Wait for the update so the function is ready for the config change
          aws lambda wait function-updated \
            --function-name ${{ env.LAMBDA_FUNCTION_NAME }}

          echo "Code deployment successful!"

      # --- STEP 2: Update the Environment Variables ---
      - name: Update Environment Variables
        run: |
          echo "Updating environment variables..."
          
          aws lambda update-function-configuration \
            --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
            --environment "Variables={ \
              TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}, \
              OMDB_API_KEY=${{ secrets.OMDB_API_KEY }}, \
          
              SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}, \
          
              PORT=${{ vars.PORT }}, \
              BUILD_ENV=${{ env.BUILD_ENV }}, \
          
              DB_NAME=${{ secrets.DB_NAME }}, \
              DB_PORT=${{ secrets.DB_PORT }}, \
          
              DB_APP_USER=${{ secrets.DB_APP_USER }}, \
              DB_APP_PASSWORD=${{ secrets.DB_APP_PASSWORD }}, \
              DB_HOST_POOLING=${{ secrets.DB_HOST_POOLING }}, \
          
              DB_MIGRATOR_USER=${{ secrets.DB_MIGRATOR_USER }}, \
              DB_MIGRATOR_PASSWORD=${{ secrets.DB_MIGRATOR_PASSWORD }}, \
              DB_HOST_MIGRATOR=${{ secrets.DB_HOST_MIGRATOR }}, \
          
              REDIS_ENDPOINT=${{ secrets.REDIS_ENDPOINT }}, \
          
              SENDER_EMAIL=${{ vars.SENDER_EMAIL }}, \
          
              JWT_SECRET=${{ secrets.JWT_SECRET }}, \
              JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }} \
          
              AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
              AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
              AWS_REGION=${{ vars.AWS_REGION }} \

            }"
          
          # Wait again to ensure the config change is applied before finishing
          aws lambda wait function-updated \
            --function-name ${{ env.LAMBDA_FUNCTION_NAME }}
